version: '3.9'

services:
  app:
    image: ruby
    working_dir: /app
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
      - gemconfig:/root/.local/share/gem
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379/0
    command: "ruby server.rb"

  postgres:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
  redis:
    image: redis


volumes:
  rubygems:
  gemconfig:
  pgdata:
  


